Feature#1
WW-DH/wecomm-fe pull request #5
Opened 2023-05-30 04:28 UTC by koline-1

### PR 설명:
- 회원가입 form을 작성하였습니다.

### 관련 Issue:
- #1 

### 추가 사항:
- BE 작업 후 회원가입 처리 및 아이디 중복검사 로직 추가가 필요합니다.
- antd form 형식에서 select는 div안에 들어갈 경우 작동이 안되어 style attribute에 css를 추가하였습니다.

### (Optional) 구현 스크린샷:
- 
![image](https://github.com/WW-DH/wecomm-fe/assets/125340956/58776f1a-43c2-481a-b721-ed8d2154b25c)

2023-06-03 11:45 UTC, dongheeYoo requested changes
의견 남깁니다~!

2023-06-03 11:45 UTC, dongheeYoo commented on src/components/SignUpPage/index.tsx
> +            },
rule 에 이미 중복된 ID를 체크하는 과정이 필요할 것 같습니다.

```
{
              validator: checkUserId,
              validateTrigger: "onBlur",
},
```
예시)
```
const checkUserId = (_: any, value: any) => {
    // TODO: api를 통해 ID 중복 체크
    return new Promise((resolve, reject) => {
      if (!value) return resolve("");
      //else return reject(new Error("중복된 아이디"));
    });
  };
```

2023-06-03 11:45 UTC, dongheeYoo commented on src/components/SignUpPage/index.tsx
> +        </Form.Item>
비밀번호 확인 과정을 추가해 보는건 어떨까요?
```
<Form.Item
          name={"confirm-password"}
          rules={[
            { required: true, message: "비밀번호를 확인해주세요." },
            ({ getFieldValue }) => ({
              validator(_, value) {
                if (!value || getFieldValue("password") === value) {
                  return Promise.resolve();
                }
                return Promise.reject(new Error("비밀번호가 맞지 않습니다."));
              },
            }),
          ]}
          label="비밀번호 확인"
        >
          <div className="input-container">
            <Input type="password" placeholder="비밀번호를 확인해주세요." />
          </div>
</Form.Item>
```

2023-06-03 11:45 UTC, dongheeYoo commented on src/components/SignUpPage/index.tsx
> +            <Input.Password placeholder="비밀번호를 입력해주세요." />
`<Input type="password" placeholder="비밀번호를 입력해주세요." />`

2023-06-03 11:48 UTC, dongheeYoo reviewed
vite.config.ts.timestamp-1681306543085.mjs

이 파일은 어떤  파일인가요?
기존의 vite.config.ts 파일에 vite config가 들어가는데 추가된 이유가 궁금합니다

2023-06-03 12:17 UTC, dongheeYoo commented on src/components/SignUpPage/style.scss
> +}
`.input-cotainer`를 직접 설정해여 div를 form.item 에 넣는것 보다는,
`.ant-form-item` / `.terms-input-container` 를 사용하면 antd form 안에 사용되는
요소들의 style을 지정할 수 있습니다!

2023-06-08 12:29 UTC, dongheeYoo commented on src/components/SignUpPage/style.scss
> +}
[188c8b8](https://github.com/WW-DH/wecomm-fe/pull/5/commits/188c8b8dad348fb7ba8e0a263221de26d86035ca)

2023-06-09 00:52 UTC, koline-1 reviewed
bb4c8cc71e4cd730dd183d0b782e05911740805e
수정 사항 요약 남깁니다.

2023-06-09 00:52 UTC, koline-1 commented on src/components/SignUpPage/index.tsx
> +    if (value?.length < 4 || value?.length > 20) {
length 따로 선언 없이 value?.length로 수정 했습니다.

2023-06-09 00:52 UTC, koline-1 commented on src/components/SignUpPage/index.tsx
> +    if (value?.length < 8 || value?.length > 20) {
length 따로 선언 없이 value?.length로 수정 했습니다.

2023-06-09 00:52 UTC, koline-1 commented on src/components/SignUpPage/index.tsx
> -            htmlType="button"
버튼 onClick 삭제 및 타입 submit으로 수정했습니다.

2023-06-09 00:52 UTC, koline-1 commented on src/components/SignUpPage/index.tsx
> -            Submit
버튼 문구 '회원가입'으로 수정했습니다.

2023-06-09 00:53 UTC, koline-1 commented
> vite.config.ts.timestamp-1681306543085.mjs
> 
> 이 파일은 어떤 파일인가요? 기존의 vite.config.ts 파일에 vite config가 들어가는데 추가된 이유가 궁금합니다

bb4c8cc71e4cd730dd183d0b782e05911740805e 에서 삭제 되었습니다,

2023-06-10 12:12 UTC, dongheeYoo approved these changes
LGTM 👍

2023-06-12 02:45 UTC, merged